language: objective-c
osx_image: xcode7
xcode_project: saml-ios-app.xcworkspace
xcode_scheme: saml-ios-app
xcode_sdk: iphonesimulator

notifications:
  irc: "irc.freenode.org#feedhenry"

branches:
  only:
    - master